# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yg16z2yBeNOcJuXexY01k5J7ziWgyzbw
"""

number=int(input('masukkan angka yang lebih besar dari 0: '))
if number % 2 == 0:
  print(number,'adalah angka genap')
else:
  print(number,'angka ganjil')

h=int(input('masukkan bilangan :'))
if h % 2 ==0 and h % 3 == 0 and h % 7 ==0:
  print('benar')
else:
  print('salah')

z=int(input('apel dibagikan kepada berapa orang : '))
sisa1 =int(input('berapa jumlah yang akan disisikan: '))
j=int(input('berapa jumlah apel: '))
sisa2=j-sisa1
jk=sisa1/z
print('masing-masing yang mendapatkan apel',jk)
print('sisa apel adalah: ', sisa1)